name: CI Workflow

on:
  workflow_call:
    inputs:
      flutter-version:
        description: 'Flutter version'
        required: false
        default: "stable"
        type: string
      run-dcm:
        description: 'Should run DCM'
        required: false
        default: true
        type: boolean
      melos-commands:
        description: 'List of melos commands to run (one per line)'
        required: false
        default: ""
        type: string
    secrets:
      token:
        description: 'Github token'
        required: true

jobs:
  test:
    name: Run tests for all packages
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout mix repo
        uses: actions/checkout@v4
      
      - name: Install FVM
        shell: bash
        run: |
          curl -fsSL https://fvm.app/install.sh | bash
          echo "$HOME/fvm/bin" >> $GITHUB_PATH

      - name: Setup Flutter via FVM
        shell: bash
        run: |
          fvm use ${{ inputs.flutter-version }} --force
          echo "$HOME/fvm/versions/${{ inputs.flutter-version }}/bin" >> $GITHUB_PATH

      - name: Flutter Doctor
        shell: bash
        run: flutter doctor

      - name: Setup Melos
        uses: bluefireteam/melos-action@v3

      - uses: invertase/github-action-dart-analyzer@v1
        with:
          fatal-infos: false

      - name: Install DCM
        if: ${{ inputs.run-dcm }}
        uses: CQLabs/setup-dcm@v2
        with:
          github-token: ${{ secrets.token }}

      - name: Run melos commands
        if: ${{ inputs.melos-commands != '' }}
        shell: bash    
        run: ${{ inputs.melos-commands }}

      - name: Run Test
        run: |
          melos run ci
        shell: bash