name: Flutter CI

on:
  workflow_call:
    inputs:
      min_coverage:
        description: "Minimum code coverage percentage required"
        required: false
        default: 80
        type: number

concurrency:
  group: flutter-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Flutter Tests
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install root dependencies
        run: flutter pub get

      - name: Analyze root project
        run: flutter analyze

      - name: Install DCM
        uses: CQLabs/setup-dcm@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run DCM
        run: dcm analyze .
        shell: bash

      - name: Run root tests
        run: flutter test --no-pub --coverage

      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1
        with:
          ref: v2.3

      - name: Comment Coverage Analysis
        if: github.event_name == 'pull_request'
        uses: ./.github/workflows/coverage-comment.yml
        with:
          coverage_file: coverage/lcov.info
          min_coverage_threshold: ${{ inputs.min_coverage }}